### ISSUE TITLE
LEI-1: Ingest LEI mappings to OpenCorporates identifiers

### ISSUE THREAD

**Issue by tiredpixel** [openownership/register-sources-oc#11]
### Tasks

- [ ] Add an Elasticsearch index for LEI identifier mappings
- [ ] Add repository with method to upsert a mapping from opencorporates identifier to LEI identifier
- [ ] Add CSV parser in register-oc-ingester to process CSV file which will accept a filename for the CSV and insert parsed mappings into Elasticsearch
- [ ] Add task to register-oc-ingester calling this functionality
- [ ] Add README instructions for performing import for this file when ingesting bulk data for OpenCorporates

### Estimate

12h

### References

- _Estimate for adding LEIs identifiers_ (PDF)—
  _T1: Ingest LEI mappings to OpenCorporates identifiers_
- https://github.com/openownership/register-sources-oc/issues/8
- https://knowledge.opencorporates.com/knowledge-base/lei-legal-entity-identifier/

cc @StephenAbbott, @spacesnottabs

**Comment by tiredpixel** [comment]
### Clarifications and Questions from Discussion

- LEIs should be imported into a new Elasticsearch index; existing indexes should not be updated.
- Upsert refers to the LEIs being imported, not any other existing documents in other indexes.
- What happens if a row gets removed from the CSV file?
- Should there be a 'last seen' field tracked—which would make the import process far slower, as every document would need to be updated?
- Where is the document of mappings being obtained from? Is it contained within the existing SFTP server (e.g. 'additional identifiers'), or is it downloaded from some other URL?
- Is the LEI present within the API responses?
- Is the LEI in fact already present within the Athena data?

cc @spacesnottabs

**Comment by StephenAbbott** [comment]
Both @kd-ods and @radix0000 have been doing work recently which means they might be able to help answer several of the questions above... ☝️

**Comment by kd-ods** [comment]
I'm not sure we can be much help. These questions are more about how the oc-lei mappings are accessible, I think.

**Comment by tiredpixel** [comment]
Setup PRs:

- https://github.com/openownership/register-ingester-oc/pull/9
- https://github.com/openownership/register-sources-oc/pull/16

**Comment by tiredpixel** [comment]
After various discussions and joint investigations with @spacesnottabs, and running the OpenCorporates additional identifiers imports myself (getting setup and marking various fixes along the way), the following conclusions have been reached:

### Tasks

> Add an Elasticsearch index for LEI identifier mappings

Not necessary; the existing `add_ids` index is sufficient. This may not yet be present in production, but the code has already been written prior to this LEI work. I verified that it works as expected.

> Add repository with method to upsert a mapping from opencorporates identifier to LEI identifier

Not necessary.

> Add CSV parser in register-oc-ingester to process CSV file which will accept a filename for the CSV and insert parsed mappings into Elasticsearch

Not necessary.

> Add task to register-oc-ingester calling this functionality

Not necessary; use existing Additional Identifiers Monthly Import process tasks (updated and fixed as part of this investigatory work).

> Add README instructions for performing import for this file when ingesting bulk data for OpenCorporates

Patches submitted in PRs.

### Clarifications and Questions from Discussion

> LEIs should be imported into a new Elasticsearch index; existing indexes should not be updated.

Already takes place in `add_ids` index.

> Upsert refers to the LEIs being imported, not any other existing documents in other indexes.

Existing process.

> What happens if a row gets removed from the CSV file?

At present, nothing.

> Should there be a 'last seen' field tracked—which would make the import process far slower, as every document would need to be updated?

Not at present.

> Where is the document of mappings being obtained from? Is it contained within the existing SFTP server (e.g. 'additional identifiers'), or is it downloaded from some other URL?

Obtained from existing SFTP server; e.g. `/oc-sftp-prod/open_ownership/2023-08-01/additional_identifiers.csv.gz`.

> Is the LEI present within the API responses?

Not currently checked, since it's available in the bulk data from SFTP.

> Is the LEI in fact already present within the Athena data?

Yes, but only once the additional identifiers bulk data has been imported.

> A large proportion of the task will be deciding where to get the data from.

Data is obtained from the SFTP bulk data file, as above.

### Elasticsearch import

LEI data was successfully imported into a local Elasticsearch cluster:

![Screenshot from 2023-08-08 16-26-38](https://github.com/openownership/register-sources-oc/assets/889632/9e889d04-dcbc-4be8-93ef-9332499b08d9)

### References

These include work done in getting set up with the OpenCorporates imports, updating those processes, documenting latest processes, and making various fixes.

- https://github.com/openownership/register-sources-bods/pull/24
- https://github.com/openownership/register-transformer-psc/pull/21
- https://github.com/openownership/register-v2/pull/18
- https://github.com/openownership/register-common/pull/11
- https://github.com/openownership/register-common/pull/10
- https://github.com/openownership/register-sources-oc/pull/16
- https://github.com/openownership/register-ingester-oc/pull/9 (tests failing because of existing failure on `main` branch)

**Comment by tiredpixel** [comment]
@StephenAbbott, I think we're ready to close this ticket, if you're happy. (I don't think there are any In Testing, etc. states for this repo.)

**Comment by StephenAbbott** [comment]
@tiredpixel Sure. Please go ahead and close the ticket ✅
